[package]
name = "random_graph"
version = "0.1.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]

[dependencies]
timely = "0.3.0"
differential-dataflow = { path = "../../../" }
dd_server = { path = "../../" }
rand="0.3.13"

[lib]
crate-type = ["dylib"]