[package]

name = "differential-dataflow"
version = "0.7.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]

description = "An incremental data-parallel dataflow platform"

# These URLs point to more information about the repository
documentation = "https://docs.rs/differential-dataflow"
homepage = "https://github.com/frankmcsherry/differential-dataflow"
repository = "https://github.com/frankmcsherry/differential-dataflow.git"
keywords = ["differential", "dataflow"]
license = "MIT"

[dev-dependencies]
indexmap = "1.0.1"
rand="0.4"
byteorder="1"
itertools="^0.7"
graph_map = { git = "https://github.com/frankmcsherry/graph-map.git" }

[dependencies]
abomonation = { git = "https://github.com/frankmcsherry/abomonation" }
abomonation_derive = "0.3"
timely_sort="0.1.6"
timely = { git = "https://github.com/frankmcsherry/timely-dataflow", tag = "v0.7.0" }
fnv="1.0.2"

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units=4
