[package]

name = "differential-dataflow"
version = "0.0.2"
authors = ["Frank McSherry <fmcsherry@me.com>"]

description = "An incremental data-parallel dataflow platform"

# These URLs point to more information about the repository
documentation = "https://github.com/frankmcsherry/differential-dataflow"
homepage = "https://github.com/frankmcsherry/differential-dataflow"
repository = "https://github.com/frankmcsherry/differential-dataflow.git"
keywords = ["differential", "dataflow"]
license = "MIT"

#[dependencies.graph_map]
#git="https://github.com/frankmcsherry/graph-map.git"

[dev-dependencies]
getopts="0.2.14"
rand="0.3.13"
byteorder="0.4.2"

[dependencies]
timely="^0.0.12"
timely_sort="^0.1.1"
timely_communication="^0.1.3"
itertools="0.4"
time = "0.1.34"
fnv="1.0.2"

[features]
default = []
logging = ["timely/logging"]

#[profile.release]
#opt-level = 3
#debug = true
#rpath = false
#lto = false
#debug-assertions = false
