
[package]

name = "differential-dataflow"
version = "0.0.1"
authors = ["Frank McSherry <fmcsherry@me.com>"]

description = "An incremental data-parallel dataflow platform"

# These URLs point to more information about the repository
documentation = "https://github.com/frankmcsherry/differential-dataflow"
homepage = "https://github.com/frankmcsherry/differential-dataflow"
repository = "https://github.com/frankmcsherry/differential-dataflow.git"
keywords = ["differential", "dataflow"]
license = "MIT"

# [dependencies.timely]
# git="https://github.com/frankmcsherry/timely-dataflow.git"
# path="../timely-dataflow"

[dependencies.graph_map]
git="https://github.com/frankmcsherry/graph-map.git"

# [dependencies.timely_sort]
# git="https://github.com/frankmcsherry/radix-sort.git"

# [dependencies.sorting]
# path="../sorting"

[dev-dependencies]
getopts="*"
rand="*"
byteorder="*"

[dependencies]
timely_communication="*"
timely_sort="*"
timely="*"
itertools="0.4"
time = "*"
fnv="*"
rc="*"

[features]
default = []
logging = ["timely/logging"]

#[profile.release]
#opt-level = 3
#debug = true
#rpath = false
#lto = false
#debug-assertions = false
