[package]

name = "differential-dataflow"
version = "0.5.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]

description = "An incremental data-parallel dataflow platform"

# These URLs point to more information about the repository
documentation = "https://github.com/frankmcsherry/differential-dataflow"
homepage = "https://github.com/frankmcsherry/differential-dataflow"
repository = "https://github.com/frankmcsherry/differential-dataflow.git"
keywords = ["differential", "dataflow"]
license = "MIT"

[dev-dependencies]
getopts="0.2.14"
rand="0.3.13"
byteorder="0.4.2"
itertools="^0.6"
serde_json = "1.0"
#pikkr = { git = "https://github.com/pikkr/pikkr" }
graph_map = { git = "https://github.com/frankmcsherry/graph-map.git" }

[dependencies]
abomonation = "0.5"
abomonation_derive = "0.3"
timely_sort="0.1.6"
timely_communication = "0.5"
timely = { git = "https://github.com/frankmcsherry/timely-dataflow" }
fnv="1.0.2"

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units=4
