[package]

name = "differential-dataflow"
version = "0.0.4"
authors = ["Frank McSherry <fmcsherry@me.com>"]

description = "An incremental data-parallel dataflow platform"

# These URLs point to more information about the repository
documentation = "https://github.com/frankmcsherry/differential-dataflow"
homepage = "https://github.com/frankmcsherry/differential-dataflow"
repository = "https://github.com/frankmcsherry/differential-dataflow.git"
keywords = ["differential", "dataflow"]
license = "MIT"

[dependencies.graph_map]
git="https://github.com/frankmcsherry/graph-map.git"

[dev-dependencies]
getopts="0.2.14"
rand="0.3.13"
byteorder="0.4.2"

[dependencies.timely]
git="http://github.com/frankmcsherry/timely-dataflow"

[dependencies]
abomonation="0.4.4"
timely_sort="0.1.5"
timely_communication="0.1.5"
itertools="0.4"
fnv="1.0.2"
linear-map = "0.0.4"
vec_map = "0.6.0"

[features]
default = []
logging = ["timely/logging"]

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
