
[package]

name = "differential-dataflow"
version = "0.0.1"
authors = ["Frank McSherry <fmcsherry@me.com>"]

description = "An incremental data-parallel dataflow platform"

# These URLs point to more information about the repository
documentation = "https://github.com/frankmcsherry/differential-dataflow"
homepage = "https://github.com/frankmcsherry/differential-dataflow"
repository = "https://github.com/frankmcsherry/differential-dataflow.git"
keywords = ["differential", "dataflow"]
license = "MIT"

[dependencies.graph_map]
git="https://github.com/frankmcsherry/graph-map.git"

[dev-dependencies]
getopts="*"
rand="*"
byteorder="*"

[dependencies]
timely="*"
timely_sort="*"
timely_communication="*"
itertools="0.4"
time = "*"
fnv="*"
rc="*"

[features]
default = []
logging = ["timely/logging"]

#[profile.release]
#opt-level = 3
#debug = true
#rpath = false
#lto = false
#debug-assertions = false
