[package]

name = "differential-dataflow"
version = "0.8.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]

description = "An incremental data-parallel dataflow platform"

# These URLs point to more information about the repository
documentation = "https://docs.rs/differential-dataflow"
homepage = "https://github.com/frankmcsherry/differential-dataflow"
repository = "https://github.com/frankmcsherry/differential-dataflow.git"
keywords = ["differential", "dataflow"]
license = "MIT"

[dev-dependencies]
indexmap = "1.0.1"
rand="0.4"
byteorder="1"
itertools="^0.7"
serde_json = "1.0"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
abomonation = "0.7"
abomonation_derive = "0.3"
timely_sort="0.1.6"
#timely = "0.8"
#timely = { git = "https://github.com/frankmcsherry/timely-dataflow", branch = "operate_rework" }
timely = { path = "../timely-dataflow/" }
fnv="1.0.2"
graph_map = "0.1"

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units=4
