[package]
name = "dogsdogsdogs"
version = "0.1.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]

[dependencies.graph_map]
git="https://github.com/frankmcsherry/graph-map.git"

[dependencies]
abomonation = "0.7"
abomonation_derive = "0.3"
timely = { git = "https://github.com/frankmcsherry/timely-dataflow" }
timely_sort="0.1.6"
differential-dataflow = { path = "../" }
