[package]
name = "dd_server"
version = "0.1.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]

[dependencies.differential-dataflow]
path="../"

[dependencies]
rand="0.3.13"
libloading="*"
timely_communication="0.1.8"
timely="0.3.0"