[package]
name = "tpchlike"
version = "0.1.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]

[dependencies.differential-dataflow]
git="https://github.com/frankmcsherry/differential-dataflow"

[dependencies.arrayvec]
git="https://github.com/bluss/arrayvec"

[dependencies]
timely="0.2.0"
abomonation="0.4.5"
