[package]
name = "tpchlike"
version = "0.1.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]

[dependencies]
timely = "0.3.0"
differential-dataflow = { path = "../" }
arrayvec = { git = "https://github.com/bluss/arrayvec" }
abomonation="0.4.5"
