[package]
name = "advent_of_code_2017"
version = "0.1.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]

[dependencies]
differential-dataflow = { path = "../" }
timely = { git = "https://github.com/frankmcsherry/timely-dataflow" }