[package]
name = "hector"
version = "0.1.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]

[dependencies.graph_map]
git="https://github.com/frankmcsherry/graph-map.git"

[dependencies]
timely = "0.3.0"
differential-dataflow = { path = "../" }